### ISSUE TITLE
About paper reproduction

### ISSUE THREAD

**Issue by gravity5212** [zehuiwu/MMML#3]
I would like to know if the following results you obtained in the paper are using the rob_d2v_cc_context module in the code？
result:ACC2Has0 F1Has0 ACC2Non0 F1Non0 ACC7 MAE Corr： 87.24 87.18 88.02 88.15 55.74 49.22 81.37

**Comment by zehuiwu** [comment]
Hi, we have updated the new results! Please use the updated code (rob_d2v_cme_context) to replicate the results.
