### ISSUE TITLE
mosei音频提取时报错MoviePy error: failed to read the duration of file data/mosei/Raw/72tXTrSXoMk/6-edited.mp4.

### ISSUE THREAD

**Issue by JunchenHuang777** [zehuiwu/MMML#4]

**Comment by zehuiwu** [comment]
Hi, I can not reproduce this bug, but I have fixed other bugs in extra_audio.py when processing MOSEI audio. Please try again with the updated code. If this bug persists, you can try adding the file name to the invalid_files list on line 97 to skip editing.
